FROM ghcr.io/open-webui/pipelines:git-adec657-cuda

USER root

COPY requirements.txt /app/pipelines

RUN pip install --no-cache-dir -r /app/pipelines/requirements.txt

COPY ./prod/*.py /app/pipelines
COPY ./dev/*.py /app/pipelines
COPY ./libs /app/libs

EXPOSE 9099

